# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='login.User')),
                ('likers', models.ManyToManyField(related_name='faves', to='login.User')),
            ],
        ),
    ]
